version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shoppro_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shoppro_db
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shoppro_rabbitmq
    ports:
      - "5672:5672"     # uygulamanın bağlanacağı port
      - "15672:15672"   # yönetim arayüzü (UI)
    environment:
      RABBITMQ_DEFAULT_USER: devuser
      RABBITMQ_DEFAULT_PASS: devpass

volumes:
  pgdata:
