server:
  address: 0.0.0.0
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shoppro_db
    username: devuser
    password: devpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: devuser
    password: devpass
